services:
  app:
    image: saraamas/backendsaas:version1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8020:8020"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/saasdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 26082010
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: saasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 26082010
    ports:
      - "5432:5432"
