services:
  app:
    image: saraamas/backendsaas:version1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8020:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

