package com.example.qms.reservation.dto;

import com.example.qms.reservation.Reservation;
import com.example.qms.queue.Queue;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.sql.Timestamp;
import java.util.UUID;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class ReservationDTO {
    private UUID id;              // Unique identifier for the reservation
    private String token;         // Token generated by the queue system
    private Integer position;     // Queue position for the reservation
    private String email;         // User's email for the reservation
    private String status;        // Status of the reservation (e.g., pending, completed)
    private Timestamp joinAt;          // Timestamp when the reservation was made
    private UUID iDqueue;


    public ReservationDTO(Reservation reservation) {
    }
}
